# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 05:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0005_auto_20170530_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidded_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itembid', to='profiles.Item')),
                ('owner_bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidowned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
