# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_biditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='biditem',
            name='bid_cost',
            field=models.IntegerField(default=0),
        ),
    ]
